language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - chmod +x gradlew

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-ktor .
  - docker tag simple-ktor sergeikarimov/simple-ktor:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sergeikarimov/simple-ktor